# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

baseurl:          /synvert

# Setup
title:            Synvert
tagline:          'syntax + convert'
description:      'synvert is used to convert ruby code to better syntax.'
url:              https://github.com/xinminlabs/synvert

author:
  name:           'Xinmin Labs'
  url:            http://xinminlabs.com

github:
  repo:           https://github.com/xinminlabs/synvert
